/**
 * migrate-airtable-targets.ts
 *
 * Reads Airtable stock-targets JSON exports (paginated) and outputs
 * D1-compatible INSERT statements for the `stock_targets` table.
 *
 * Depends on: scripts/output/item-name-to-id.json (generated by migrate-airtable-items.ts)
 *
 * Usage: npx tsx scripts/migrate-airtable-targets.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface AirtableRecord {
  id: string;
  createdTime: string;
  fields: {
    'Target ID'?: string;
    'Target Count'?: number;
    'Last updated'?: string;
    Item?: string[];
    Station?: string[];
    [key: string]: unknown;
  };
}

interface AirtableExport {
  records: AirtableRecord[];
  offset?: string;
}

// ---------------------------------------------------------------------------
// Station mapping
// ---------------------------------------------------------------------------

const STATION_NAME_TO_ID: Record<string, number> = {
  'Station 10': 10,
  'Station 13': 13,
  'Station 18': 18,
  'Station 20': 20,
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse station name from Target ID field.
 * Format: "Item Name - Station XX"
 * Some have quotes: "\"IV Catheter, 22g Each\" - Station 10"
 */
function parseTargetId(targetId: string): { itemName: string; stationName: string } | null {
  // Match " - Station XX" at the end
  const match = targetId.match(/^(.+?)\s*-\s*(Station \d+)$/);
  if (!match) return null;

  let itemName = match[1].trim();
  // Strip surrounding quotes
  itemName = itemName.replace(/^"+/, '').replace(/"+$/, '');
  // Collapse doubled/tripled quotes to single (Airtable artifact: 9/32"" → 9/32")
  itemName = itemName.replace(/""+/g, '"');
  // Normalize whitespace
  itemName = itemName.replace(/\s+/g, ' ').trim();

  return { itemName, stationName: match[2] };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const dataDir = '/home/dcdev/ems-inventory-data';
  const outputDir = path.resolve(__dirname, 'output');
  const outputPath = path.join(outputDir, 'stock_targets.sql');
  const itemMapPath = path.join(outputDir, 'item-name-to-id.json');

  // Load item name→ID map
  if (!fs.existsSync(itemMapPath)) {
    console.error('ERROR: item-name-to-id.json not found. Run migrate-airtable-items.ts first.');
    process.exit(1);
  }
  const nameToId: Record<string, number> = JSON.parse(fs.readFileSync(itemMapPath, 'utf-8'));

  // Read all paginated stock-targets files
  const files = fs
    .readdirSync(dataDir)
    .filter((f) => f.startsWith('stock-targets-p') && f.endsWith('.json'))
    .sort();

  const allRecords: AirtableRecord[] = [];
  for (const file of files) {
    const data: AirtableExport = JSON.parse(fs.readFileSync(path.join(dataDir, file), 'utf-8'));
    allRecords.push(...data.records);
    console.log(`  ${file}: ${data.records.length} records`);
  }
  console.log(`Read ${allRecords.length} total stock target records`);

  // Process records
  const targets: Array<{
    item_id: number;
    station_id: number;
    target_count: number;
    updated_at: string;
  }> = [];

  let unmapped = 0;
  const unmappedNames = new Set<string>();

  for (const rec of allRecords) {
    const targetId = rec.fields['Target ID'];
    if (!targetId) continue;

    const parsed = parseTargetId(targetId);
    if (!parsed) {
      console.warn(`  WARNING: Could not parse Target ID: ${targetId}`);
      continue;
    }

    const stationId = STATION_NAME_TO_ID[parsed.stationName];
    if (!stationId) {
      console.warn(`  WARNING: Unknown station: ${parsed.stationName}`);
      continue;
    }

    const itemId = nameToId[parsed.itemName];
    if (!itemId) {
      unmapped++;
      unmappedNames.add(parsed.itemName);
      continue;
    }

    targets.push({
      item_id: itemId,
      station_id: stationId,
      target_count: rec.fields['Target Count'] ?? 0,
      updated_at: rec.fields['Last updated'] ?? rec.createdTime,
    });
  }

  // Build SQL
  const lines: string[] = [
    `-- migrate-airtable-targets.ts output`,
    `-- Generated: ${new Date().toISOString()}`,
    `-- ${targets.length} stock targets (${unmapped} unmapped items skipped)`,
    ``,
    `-- Stock Targets -------------------------------------------------------`,
    ``,
  ];

  for (let i = 0; i < targets.length; i++) {
    const t = targets[i];
    lines.push(
      `INSERT OR IGNORE INTO stock_targets (id, item_id, station_id, target_count, updated_at)` +
        ` VALUES (${i + 1}, ${t.item_id}, ${t.station_id}, ${t.target_count}, '${t.updated_at}');`,
    );
  }

  lines.push('');

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');

  console.log(`Wrote ${targets.length} stock targets to ${outputPath}`);
  if (unmappedNames.size > 0) {
    console.log(`  Unmapped item names (${unmappedNames.size}):`);
    for (const name of [...unmappedNames].sort()) {
      console.log(`    - ${name}`);
    }
  }
}

main();
